const products = [
   {
      "id": "1",
      "header": "Sleepandbed_Georgia",
      "image": ["/prod/matrasi/1.jpg", "/prod/matrasi/2.jpg", "/prod/matrasi/3.jpg", "/prod/matrasi/4.jpg"],
      "secondtext": "იგრძენი კომფორტი…",
      "text": "ჩვენს Dream soft პროდუქტს აქვს 3 განსხვავებული სიმკვრივის ღრუბლის ფენა და სთავაზობს ორმხრივ გამოყენებას თავის მომხმარებლებს...",
      "title": "Dream Double Face",
      "desc": "მატრასი",
      "height": "32 სმ სიმაღლე",
      "springTechnology": "7 ზონიანი ჯიბის ზამბარის ტექნოლოგია",
      "breathable": "სუნთქვადი დიზაინი",
      "doubleSided": "ორმხრივი გამოყენება",
      "supportSponge": "მაღალი სიმკვრივის საყრდენი ღრუბელი",
      "orthopedic": "ორთოპედიული სტრუქტურა"
    
  },
  {
      "id": "2",
      "header": "Sleepandbed_Georgia",
      "image": ["/prod/matrasi/1.jpg", "/prod/matrasi/2.jpg", "/prod/matrasi/3.jpg", "/prod/matrasi/4.jpg"],
      "secondtext": "როგორც ზღვის სიგრილე...",
      "text": "მიუხედავად იმისა, რომ გელის მეხსიერების ღრუბლის ფენა მისი შინაარსით ყალიბდება ადამიანის სხეულის ტემპერატურისა და წონის მიხედვით...",
      "title": "Dream Visco",
      "desc": "მატრასი",
      "height": "27 სმ სიმაღლე",
      "springTechnology": "გელის მეხსიერების ღრუბლის ტექნოლოგია",
      "breathable": "სუნთქვადი ბუნებრივი ქსოვილი",
      "orthopedic": "ორთოპედიული მხარდაჭერა",
      "material":"wool"
    
  },
  {
      "id": "3",
      "header": "Sleepandbed_Georgia",
      "image": ["/prod/matrasi/1.jpg", "/prod/matrasi/2.jpg", "/prod/matrasi/3.jpg", "/prod/matrasi/4.jpg"],
      "secondtext": "ნოსტალგიური ნიავი…",
      "text": "შექმნილია იმისთვის, რომ უზრუნველყოს სხეულის იდეალური მხარდაჭერა ძილის ან წოლის დროს...",
      "title": "Prestige Plus",
      "desc": "მატრასი",
      "height": "15 სმ სიმაღლე",
      "springTechnology": "7 ზონიანი ჯიბის ზამბარის ტექნოლოგია",
      "breathable": "სუნთქვადი",
      "doubleSided": "ორმხრივი გამოყენება",
      "supportSponge": "მაღალი სიმკვრივის საყრდენი ღრუბელი",
      "orthopedic": "ორთოპედიული დიზაინი",
       "material":"wool"
    
  },
  {
      "id": "4",
      "header": "Sleepandbed_Georgia",
      "image": ["/prod/matrasi/1.jpg", "/prod/matrasi/2.jpg", "/prod/matrasi/3.jpg", "/prod/matrasi/4.jpg"],
      "secondtext": "ალოე ვერას სასწაული და მეხსიერების ძლიერი ღრუბელი…",
      "text": "Aloevera visco, მატრასში შემავალი ვისკოს ორთოპედიული სტრუქტურის წყალობით...",
      "title": "Aloevera Visco",
      "desc": "მატრასი",
      "height": "33 სმ სიმაღლე",
      "springTechnology": "ვისკოს მეხსიერების ღრუბელი",
      "breathable": "ბუნებრივი ალოე ვერას ქსოვილი",
      "orthopedic": "ორთოპედიული მხარდაჭერა",
       "material":"latex"
    
  },
  {
   "id": "15",
   "header": "Sleepandbed_Georgia",
   "image": ["/prod/matrasi/1.jpg", "/prod/matrasi/2.jpg", "/prod/matrasi/3.jpg", "/prod/matrasi/4.jpg"],
   "secondtext": "ალოე ვერას სასწაული და მეხსიერების ძლიერი ღრუბელი…",
   "text": "Aloevera visco, მატრასში შემავალი ვისკოს ორთოპედიული სტრუქტურის წყალობით...",
   "title": "Aloevera Visco",
   "desc": "მატრასი",
   "height": "33 სმ სიმაღლე",
   "springTechnology": "ვისკოს მეხსიერების ღრუბელი",
   "breathable": "ბუნებრივი ალოე ვერას ქსოვილი",
   "orthopedic": "ორთოპედიული მხარდაჭერა",
   "material":"Knitted Fabric"

},
    { id: '5', header:"Sleepandbed_Georgia", image: ["/prod/balishi/1.jpg", "/prod/balishi/2.jpg", "/prod/balishi/3.jpg", "/prod/balishi/4.jpg"], size:"50x70 სმ", qsovili:"Tencel Fabric", item:"70% ვისკო 30% ბოჭკოვანი", title: "Dream", desc: "ბალიში",secondtext:"Dream-ის ბალიში", },
    { id: '6', header:"Sleepandbed_Georgia", image: ["/prod/balishi/1.jpg", "/prod/balishi/2.jpg", "/prod/balishi/3.jpg", "/prod/balishi/4.jpg"], title: "Harmony", size:"50x70 სმ", qsovili:"Tencel ნაქსოვი ქსოვილი", item:"40% ვისკო 40% ჰიპერ რბილი ღრუბელი 20% ბოჭკოვანი", desc: "ბალიში",secondtext:"Harmony-ს  ბალიში", },
    { id: '7', header:"Sleepandbed_Georgia", image: ["/prod/balishi/1.jpg", "/prod/balishi/2.jpg", "/prod/balishi/3.jpg", "/prod/balishi/4.jpg"], title: "Seaqual Visco", size:"50x70 სმ", qsovili:"ზღვისფერი", item:"70% ვისკო 30% ბოჭკოვანი", desc: "ბალიში",secondtext:"Seaqual Visco-ს ბალიში", },
    { id: '8', header:"Sleepandbed_Georgia", image: ["/prod/balishi/1.jpg", "/prod/balishi/2.jpg", "/prod/balishi/3.jpg", "/prod/balishi/4.jpg"], title: "Trend", size:"50x70 სმ", qsovili:"Tencel Fabric", item:"70% ვისკო 30% ბოჭკოვანი", desc: "ბალიში",secondtext:"ბალიში Trend", },
    {
      "id": "9",
      "header": "Sleepandbed_Georgia",
      "image": ["/prod/sabani/1.jpg", "/prod/sabani/2.jpg", "/prod/sabani/3.jpg", "/prod/sabani/4.jpg"],
      "title": "Wollies",
      "desc": "საბანი",
      "qsovili": "Wollies ქვილთი",
      "text": "სუნთქავს, შთანთქავს ტენს ძილის დროს და ასტაბილურებს ტემპერატურას. ბუნებრივი და მსუბუქი. შესაძლებელია სარეცხის მანქანაში გარეცხვა.",
      "size": "155x215cm – 195x215cm – 220x240cm",
      "fabric": "100% მიკრობოჭკოვანი ქსოვილი - ალოევერა ფინიში",
      "weight": "1.5 kg – 2.5 kg (depending on size)",
      "filling": "Synthetic hypoallergenic filling for softness and breathability"
  },
  {
      "id": "10",
      "header": "Sleepandbed_Georgia",
      "image": ["/prod/sabani/1.jpg", "/prod/sabani/2.jpg", "/prod/sabani/3.jpg", "/prod/sabani/4.jpg"],
      "title": "Wollies",
      "desc": "საბანი",
      "qsovili": "Wollies ქვილთი",
      "text": "სუნთქავს, შთანთქავს ტენიანობას ძილის დროს და ასტაბილურებს ტემპერატურას. ბუნებრივი და მსუბუქი. შესაძლებელია სარეცხის მანქანაში გარეცხვა.",
      "size": "155x215cm – 195x215cm – 220x240cm",
      "fabric": "100% მიკრობოჭკოვანი ქსოვილი - ალოევერა ფინიში",
      "weight": "1.5 kg – 2.5 kg (depending on size)",
      "filling": "Synthetic hypoallergenic filling for comfort and support"
  },
  {
      "id": "11",
      "header": "Sleepandbed_Georgia",
      "image": ["/prod/sabani/1.jpg", "/prod/sabani/2.jpg", "/prod/sabani/3.jpg", "/prod/sabani/4.jpg"],
      "title": "Aloevera",
      "desc": "საბანი",
      "qsovili": "Wollies ქვილთი",
      "text": "სუნთქავს, შთანთქავს ტენიანობას ძილის დროს და ასტაბილურებს ტემპერატურას. ბუნებრივი და მსუბუქი. შესაძლებელია სარეცხის მანქანაში გარეცხვა.",
      "size": "155x215cm – 195x215cm – 220x240cm",
      "fabric": "100% მიკრობოჭკოვანი ქსოვილი - ალოევერა ფინიში",
      "weight": "1.5 kg – 2.5 kg (depending on size)",
      "filling": "Soft and breathable synthetic filling, hypoallergenic"
  },
  {
      "id": "12",
      "header": "Sleepandbed_Georgia",
      "image": ["/prod/sabani/1.jpg", "/prod/sabani/2.jpg", "/prod/sabani/3.jpg", "/prod/sabani/4.jpg"],
      "title": "Aloevera",
      "desc": "საბანი",
      "qsovili": "Wollies ქვილთი",
      "text": "სუნთქავს, შთანთქავს ტენიანობას ძილის დროს და ასტაბილურებს ტემპერატურას. ბუნებრივი და მსუბუქი. შესაძლებელია სარეცხის მანქანაში გარეცხვა.",
      "size": "155x215cm – 195x215cm – 220x240cm",
      "fabric": "100% მიკრობოჭკოვანი ქსოვილი - ალოევერა ფინიში",
      "weight": "1.5 kg – 2.5 kg (depending on size)",
      "filling": "Light, hypoallergenic filling for extra comfort and temperature regulation"
  },
  {
   "id": "13",
   "header": "Sleepandbed_Georgia",
   "image": ["/prod/toperi/1.jpg", "/prod/toperi/2.jpg", "/prod/toperi/3.jpg", "/prod/toperi/4.jpg"],
   "secondtext": "დასვენების მაქსიმალური კომფორტი",
   "text": "იგი შექმნილია როგორც ძვირადღირებული პროდუქტების ალტერნატივა. ამავდროულად, რადგან ის ორმხრივია, თქვენ ყოველთვის იგრძნობთ ვისკოსა და ღრუბლის კომფორტს.",
   "title": "Product Fourteen",
   "desc": "ტოპერი",
   "height": "7 სმ სიმაღლე",
   "springTechnology": "ჰაერის ნაპრალი მხარდაჭერა",
   "breathable": "სუნთქვადი",
   "doubleSided": "ორმხრივი გამოყენება",
   "supportSponge": "მაღალი სიმკვრივის საყრდენი ღრუბელი",
   "orthopedic": "ორთოპედიული დიზაინი",
   "material": "ალოევერა"
},
{
   "id": "14",
   "header": "Sleepandbed_Georgia",
   "image": ["/prod/toperi/1.jpg", "/prod/toperi/2.jpg", "/prod/toperi/3.jpg", "/prod/toperi/4.jpg"],
   "secondtext": "კომფორტული და მდგრადი",
   "text": "შექმნილია როგორც ძვირადღირებული პროდუქტების ალტერნატივა, Hard Comfort არის თქვენს გვერდით. ჩვენ გავაერთიანეთ ალოვერას ქსოვილის ბუნებრიობა პორტატულ კომფორტთან. იყავი კომფორტული და ბუნებრივი.",
   "title": "Product Fifteen",
   "desc": "ტოპერი",
   "height": "7 სმ სიმაღლე",
   "springTechnology": "მაღალი სიმკვრივის საყრდენი ღრუბელი",
   "breathable": "სუნთქვადი",
   "doubleSided": "ორმხრივი გამოყენება",
   "supportSponge": "მაღალი სიმკვრივის საყრდენი ღრუბელი",
   "orthopedic": "ორთოპედიული დიზაინი",
   "material": "ქსოვილი"
},
{
   "id": "15",
   "header": "Sleepandbed_Georgia",
   "image": ["/prod/toperi/1.jpg", "/prod/toperi/2.jpg", "/prod/toperi/3.jpg", "/prod/toperi/4.jpg"],
   "secondtext": "დაამატეთ კომფორტის რბილი ფენა თქვენს იაფ მატრასს. ამ გზით, თქვენ შეგიძლიათ მიიღოთ თქვენთვის სასურველი კომფორტი და თან წაიღოთ სადაც არ უნდა წახვიდეთ.",
   "text": "ტოპერი, რომელიც აერთიანებს კომფორტსა და ჰიგიენას.",
   "title": "Product Sixteen",
   "desc": "ტოპერი",
   "height": "7 სმ სიმაღლე",
   "springTechnology": "ჰაერის ნაპრალი მხარდაჭერა",
   "breathable": "სუნთქვადი",
   "doubleSided": "ორმხრივი გამოყენება",
   "supportSponge": "მაღალი სიმკვრივის საყრდენი ღრუბელი",
   "orthopedic": "ორთოპედიული დიზაინი",
   "material": "მიკრო ბოჭკოვანი ქსოვილი"
}

  ];
  
  export default products;
  