import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";


const quicksand = Quicksand({
  variable: "--font-quicksand",  
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "S&B",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${quicksand.variable}  antialiased`}
      >
        <Header />
        {children}
      <Footer />
      </body>
    </html>
  );
}
